# Generated by Django 4.2.20 on 2025-04-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details_url',
            field=models.URLField(default='/static/places/default.json'),
        ),
    ]
