# Generated by Django 4.2.20 on 2025-04-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_details_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='details_url',
        ),
    ]
