# Generated by Django 4.2.20 on 2025-04-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_details_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
